### ISSUE TITLE
`Windows.Win32.Security.PSECURITY_DESCRIPTOR` should provide safe input and output

### ISSUE THREAD

**Issue by zbalkan** [microsoft/CsWin32#1009]
`Windows.Win32.Security.PSECURITY_DESCRIPTOR` struct accepts only unsafe `void*` type of `value` parameter. The return value is in the `Value` property with the type of `void*`. The unsafe pointer usage adds cognitive load on development while adding zero value to the user.

Below, you can see the usage within `GetKernelObjectSecurity` method. The signature generated by CsWin32:

```csharp
public static unsafe Windows.Win32.Foundation.BOOL GetKernelObjectSecurity(
SafeHandle Handle,
uint RequestedInformation,
Windows.Win32.Security.PSECURITY_DESCRIPTOR pSecurityDescriptor,
uint nLength,
out uint lpnLengthNeeded)
```

The way to handle `GetKernelObjectSecurity` using conventional P/Invoke calls looks like this:

```csharp
[DllImport("advapi32.dll", SetLastError = true)]
[DefaultDllImportSearchPaths(DllImportSearchPath.System32)]
internal static extern bool GetKernelObjectSecurity(
IntPtr Handle,
int RequestedInformation,
[Out] byte[] pSecurityDescriptor,
uint nLength,
out uint lpnLengthNeeded);
```

The usage now requires workarounds:
```csharp
unsafe
{
    Span<byte> newBytes = stackalloc byte[(int)bufSizeNeeded];
    var pSecurityDescriptor = new PSECURITY_DESCRIPTOR(&newBytes);
    // rest of the code
}
```

The `CsWin32` should look and behave similar, too. It should accept `byte[]` or `Span<byte>`, and return the same.

**Comment by AArnott** [comment]
CsWin32 sticks to the Win32 headers fairly closely, both for perf and correctness. We do add friendly overloads in many cases, but in structs are options are limited because of type identity requirements on .NET. In this case, we do not collapse 1-field structs into just their field and use their field directly as you propose. The metadata doesn't even indicate to us that `void* Value` is a pointer to a `byte` array as your translation would require that CsWin32 knows.

CsWin32 doesn't try to make Win32 easier that it was originally designed to be. That's an opportunity for a higher-level library that might use CsWin32 internally. Pointers and 'unsafe' code are a fundamental to p/invoke in many cases. Even without pointers, p/invoking is itself an unsafe operation.
