### ISSUE TITLE
Implement `IsBetween`/`IsKeyMessage`/`IsMouseMessage` on `MSG`

### ISSUE THREAD

**Issue by elachlan** [microsoft/CsWin32#1036]
**Is your feature request related to a problem? Please describe.**
Winforms has implemented `IsBetween`/`IsKeyMessage`/`IsMouseMessage` as extension methods to provide a reusable way to check `MessageId` values.

https://github.com/dotnet/winforms/blob/f57975a31f67ea9033468d3ec646ebf01e8fc6ed/src/System.Windows.Forms.Primitives/src/Interop/User32/WMExtensions.cs

**Describe the solution you'd like**
I'd like these to be provided against `MSG`.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by AArnott** [comment]
Do these functions have equivalents in the win32 API for C users? If so, then we could look at adding them here. If not, I'd be inclined to _not_ add these to keep CsWin32 focused as an low-level API generator rather than adding endless trimmings on top that make it easier to use, which it outside the scope.

**Comment by elachlan** [comment]
No, its just something we have implemented in winforms interop code that would be useful.
