### ISSUE TITLE
IShellItemImageFactory.GetImage should return HRESULT

### ISSUE THREAD

**Issue by myth384** [microsoft/CsWin32#1189]
## Actual behavior

Currently `IShellItemImageFactory.GetImage` returns void.

## Expected behavior

According to [the official documentation](https://learn.microsoft.com/en-us/windows/win32/api/shobjidl_core/nf-shobjidl_core-ishellitemimagefactory-getimage) it should return an `HRESULT`.

## Repro steps

1. `NativeMethods.txt` content:
```
IShellItemImageFactory
```

2. `NativeMethods.json` content (if present):
```
{
  "$schema": "https://aka.ms/CsWin32.schema.json"
}
```

3. Any of your own code that should be shared?

### Context

- CsWin32 version: 0.3.106
- Win32Metadata version (if explicitly set by project): not set
- Target Framework: net8.0-windows
- `LangVersion` (if explicitly set by project): not set

**Comment by AArnott** [comment]
CsWin32 is doing the default .NET thing: considering PreserveSig to be false by default. If a failing HRESULT were to be returned from this API, an exception would be thrown to your code. Or if you are the one implementing the interface, you should throw an exception to produce a failing HRESULT for your native caller.

If you really want an HRESULT instead of exceptions, you can add this API to the list of preservesig APIs as [described in the readme](https://github.com/microsoft/CsWin32?tab=readme-ov-file#customizing-generated-code).
