### ISSUE TITLE
Update to metadata that fixes the char* as ushort* problem

### ISSUE THREAD

**Issue by AArnott** [microsoft/CsWin32#121]

**Comment by tannergooding** [comment]
This may not be a good idea. There is some discussion in https://github.com/dotnet/corefxlab/issues/2350 about changing `char` to be `UTF8` and therefore 1-byte, rather than 2 at an opt-in level which means that `char*` for a `LPCWSTR` would now be incorrect.

Likewise, while `char*` itself is just a pointer and therefore blittable. `char`, `char[]`, and `string` are not and are only sometimes blittable (and generally require you to explicitly annotate that you want it handled as `UnmanagedType.U2` or as `CharSet.Unicode`).

**Comment by AArnott** [comment]
I am shocked to learn that `char` might be redefined as a 1-byte value. I can't imagine how much code that would break. 
I'm not sure what you're saying isn't a good idea though. `char*` *is* how anyone and everyone can represent a UTF-16 string today. `string` can be pinned today as a `char*`. It *cannot* be pinned as a `ushort*`. So while I don't have a crystal ball to foresee what the CLR may do in the future, we're generating code that needs to work well with the code people have today, which for the time being is `char*`.
