### ISSUE TITLE
SHGetFileInfo does not work

### ISSUE THREAD

**Issue by TimberStalker** [microsoft/CsWin32#1272]
## Actual behavior

For some reason, SHGetFileInfo is the only method i cant get to generate. Every other method ive tries works. Only this one doesent generate. I tried with A and W but those didnt work either.

## Expected behavior

SHGetFileInfo should be callable from PInvoke

## Repro steps

`NativeMethods.txt` content:
```
SHGetFileInfo
```

- CsWin32 version: 0.3.106
- TargetFramework: net8.0
- LangVersion: 12

**Comment by AArnott** [comment]
Likely you're targeting AnyCPU. The build should have a warning like this:

> warning PInvoke005: This API is only available when targeting a specific CPU architecture. AnyCPU cannot generate this API.

That'll be why. You can define one or more specific project platforms so that your code can still run on multiple architectures, but there is something about this specific API that varies in its native definition by arch that makes it incompatible with AnyCPU.

**Comment by TimberStalker** [comment]
That fixed the issue, thank you. I wasnt getting any warnings though.
