### ISSUE TITLE
Missing tests for MINIDUMP_TYPE, MiniDumpWriteDump, GetCurrentProcess, GetCurrentProcessId, GetCurrentThreadId.

### ISSUE THREAD

**Issue by AraHaan** [microsoft/CsWin32#224]
There may be other apis, however there are missing tests that would check generation on all 3 of the TFMs the tests try to generate for.

If this gets tested it will expose possibly where the issue might be for #221 on these apis. Oddly enough it happens with the enum as well for some unknown reason that I think should generate the enum on .NET Standard 2.0 (but that is another issue for the one I linked) and yes I tried every version of CsWin32 and they all failed the same way on these.

**Comment by AArnott** [comment]
We don't need tests for individual APIs in general. Our `FullGeneration` test already verifies that no exception is thrown for the whole metadata winmd.
If there are actual failures, or we need to test something specifically, then we add a test to make regression testing faster, since FullGeneration takes a long time to run and produces massive output.
But I see no bugs in any of these APIs. See my comments on your PR.
