### ISSUE TITLE
Mark unused entries in NativeMethods.txt as unused and offer to remove

### ISSUE THREAD

**Issue by jnm2** [microsoft/CsWin32#233]
The mirror of #232. A warning or suggestion-level diagnostic squiggle in NativeMethods.txt would be nice, if Roslyn allows that. 

Maybe fading the entry as unnecessary would even work, like how unnecessary code is faded. I haven't tried it in AdditionalFiles files, but I do know how to create faded spans in .cs files: https://github.com/dotnet/roslyn/blob/2adc0bd2f54fc71342e489784babbc933dde5f86/src/Analyzers/Core/Analyzers/SimplifyInterpolation/AbstractSimplifyInterpolationDiagnosticAnalyzer.cs#L80-L85

**Comment by jnm2** [comment]
Credit to @CameronDwyer for the idea.

**Comment by AArnott** [comment]
This may not be as clear as one might think. Suppose my NativeMethods.txt file contains `CreateFile`, and although my code does not consume that method, it uses one of the enum types that are implicitly generated to support that method. Should we:

1. Consider CreateFile to be important and not do anything
2. Indicate the user can remove `CreateFile` because that API specifically is unused, even though removing it will generate other errors
3. Be super smart and encourage the user to *replace* the `CreateFile` line with *n* more lines for the specific APIs that actually are being used?

Then there's the case where a line *is* used directly, but it still isn't necessary because it comes for free by virtue of another line that also appears in the file.

I think any of these would be fairly expensive, both in terms of complexity and at runtime. We can keep the issue active for now, but just to set expectations I don't think it'll get done any time soon (if at all).

**Comment by jnm2** [comment]
It does sound complicated. I would prefer the ability to opt in to behavior 2 (or 3).

**Comment by AraHaan** [comment]
Well some people actually prefer explicitly listing only the things they use on their NativeMethods.txt file (including enums they use if they only need specific enums and not the api functions the enum(s) are normally for) which would make it more clear what the code actually depends on.

**Comment by AArnott** [comment]
Closing to focus on more impactful work.
