### ISSUE TITLE
Generate all members in namespace from nativemethods.txt

### ISSUE THREAD

**Issue by AArnott** [microsoft/CsWin32#259]
**Is your feature request related to a problem? Please describe.**

I want to easily generate everything within a "namespace" from the metadata, whether it by structs, methods, or interfaces.

**Describe the solution you'd like**

When a namespace is named in the .txt input file, generate all members of it:

```
CreateFile
windows.win32.ai.machinelearning.directml
```

**Describe alternatives you've considered**

A special `ns:System.IO.*` syntax:

```
CreateFile
User32.*
ns:windows.win32.ai.machinelearning.directml.*
```

**Comment by wjk** [comment]
Agreed. This would make things much easier for me. What would make it even better is being able to copy the namespaces from the win32metadata file verbatim into the output C# code, instead of just flattening everything into `Microsoft.Windows.Sdk` or whatever namespace the user specified. While I might run into name-collision errors in my code if I use two different namespaces both containing a `PInvoke` (or `NativeMethods`, or whatever) class, this problem would be easy to fix by adding e.g. `using RibbonNativeMethods = Windows.Win32.UI.Ribbon.NativeMethods` to the affected files.

**Comment by AArnott** [comment]
Thanks for your thoughts, @wjk. In fact our latest version (in our CI feed) already generates types into namespaces.
