### ISSUE TITLE
DeleteObjectSafeHandle can't be passed to GetObject (again)

### ISSUE THREAD

**Issue by jnm2** [microsoft/CsWin32#275]
A separate issue was previously fixed (https://github.com/microsoft/CsWin32/issues/116).

When updating from 0.1.445-beta to 0.1.474-beta, GetObject starts taking only HGDIOBJ with no overloads that accept the (owned) DeleteObjectSafeHandle that I had been passing.

Targeting `net35;net48;net5.0-windows`. Using C# 9.

No overloads no matter which target framework context I use:

![image](https://user-images.githubusercontent.com/8040367/119171376-80fb0e00-ba32-11eb-870e-3249a73e37e2.png)

**Comment by AArnott** [comment]
HGDIOBJ isn't recognized as a handle typedef because it has no `[RAIIFree("DeleteObject")]` attribute as all its "derived types" do. 
We have a hard-coded bit to treat it as a handle anyway for one case, but not for generating friendly overloads. If this ever worked, I suppose this was because the metadata used some other struct for `GetObject`.
But we should make this work, certainly.
