### ISSUE TITLE
CreateSymbolicLink returns `byte` instead of `bool` for `BOOLEAN`

### ISSUE THREAD

**Issue by jnm2** [microsoft/CsWin32#278]
https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-createsymboliclinkw#return-value

### Context

- CsWin32 version: [e.g. `0.1.422-beta`]
- Target Framework: [e.g. `net5.0-windows`]
- `LangVersion`: 9

**Comment by AArnott** [comment]
We return `byte` because that's what the metadata does.

![image](https://user-images.githubusercontent.com/3548/121429607-56ff8200-c934-11eb-84e8-7ebce3054ce7.png)

My guess is in C, `BOOLEAN` is a 1-byte value. In C# `boolean` isn't (always?) a 1-byte value so we have to use `byte` on the extern method declaration.

It's unfortunate that C#'s type safety makes your boolean conditions have to add `!=0` in such cases. But even in the docs, they speak in terms of `zero` and `nonzero` rather than boolean terms of `true` and `false`.

**Comment by jnm2** [comment]
Could you please reconsider?

> My guess is in C, BOOLEAN is a 1-byte value. In C# boolean isn't (always?) a 1-byte value so we have to use byte on the extern method declaration.

In C#, `bool` is always a 1-byte value. The marshaller does different things depending on whether you annotate the extern method's return type with MarshalAsAttribute. I believe it defaults to expanding it to four bytes since the majority of Windows APIs use `BOOL` which is defined as four bytes.

I don't think it's true that you have to use `byte` on the extern method declaration.

> But even in the docs, they speak in terms of zero and nonzero rather than boolean terms of true and false.

Since this point doesn't cause you to return `byte`/`int` for https://docs.microsoft.com/en-us/windows/win32/api/wingdi/nf-wingdi-bitblt#return-value even though it uses the terms 'zero' and 'nonzero' for the return value, this point should not apply here.

This is a usability issue, and all signs seem to point to saying it would be consistent to do something.

**Comment by tannergooding** [comment]
> In C#, bool is always a 1-byte value

Yes. C# defines `bool` as `1-byte` where `0` is `false` and `1` is `true`
The JIT also defines `bool` as `1-byte` but defines `0` to be `false` and `not zero` (any other bit pattern) to be `true`

The P/Invoke marshaller defaults to treating `bool` as a Windows `BOOL`, that is a 4-byte integer (I don't remember if the COM marshaller differs).
The P/Invoke marshaller defaults to normalizing `bool` to `0` or `1` (whether the default 4-byte bool or an explicit `U1/I1` bool, or one of the other bool types).

The normalizing of the bool will result in a stub method being generated and that stub method may or may not be inlined and so you may incur an additional `call`, on top of the P/Invoke call.
Normalizing/converting in C# via an explicit wrapper is "better" for many reasons, including having the logic be visible/easily updated (unlike the runtime logic) and because you can explicitly mark it `AggressiveInlining` if that's appropriate to remove the additional indirection.

CC. @AaronRobinsonMSFT

**Comment by tannergooding** [comment]
Normalizing can have negative side effects, such as losing state/information for certain APIs (not all APIs exclusively return Win32 `TRUE`/`FALSE` or `0`/`1` and some could return say `-1` or `2` or another value to represent additional state).

Likewise, since C# can't overload based on return type, its not trivial to expose one that returns `bool` and one that doesn't.

**Comment by AaronRobinsonMSFT** [comment]
@AArnott I agree with @tannergooding's opinion here and based on your response I think yours as well. I will say that @jnm2 does have a point about usability and do appreciate that opinion. It might be useful to define the goals and non-goals of CsWin32 in the [`README.md`](https://github.com/microsoft/CsWin32/blob/main/README.md). I think the minimum I would answer is: What is the purpose of CsWin32? Is it to define the most optimal, accurate, or natural UX P/Invoke? Is there a relative priority based on some cost? I think having the goals defined would help guide these sorts of questions.

**Comment by AArnott** [comment]
At the moment, we're just doing what the metadata says. There is no way for us to know that semantically it's intended to be a boolean. I'm going to move the issue to the metadata repo and we can continue the discussion there.
It would be great for the metadata to reflect that this is a 1-byte boolean value so that projections *can* make the decision. 

As for the usability vs perf trade-off, we try to get most of both worlds by generating the `extern` method to reflect the header file as closely as possible, and then we add one or more "friendly" overloads that wrap the behavior. We could do the same thing here, although when only the return type changes, it means the "overload" would have a different name. We already do this for methods that return handles where the friendly overload has a `_SafeHandle` suffix. We could do something similar here with a `_bool` suffix.
