### ISSUE TITLE
When not targeting specific CPU archetecture the ExceptionPointers member of MINIDUMP_EXCEPTION_INFORMATION can be IntPtr (or nint).

### ISSUE THREAD

**Issue by AraHaan** [microsoft/CsWin32#336]
I use AnyCPU and I have it generate MiniDumpWriteDump and use the ``GetExceptionPointers()`` function on the runtime to get the exception pointers as an ``nint`` (IntPtr) and as such I wanted to avoid the cast entirely (I hate casts from 1 pointer type to another as it requires ``unsafe``).

I even tried doing:

```cs
namespace Windows.Win32.System.Diagnostics.Debug
{
    using global::System;
    using Windows.Win32.Foundation;

    /// <summary>Contains the exception information written to the minidump file by the MiniDumpWriteDump function.</summary>
    /// <remarks>
    /// <para><see href = "https://docs.microsoft.com/windows/win32/api//minidumpapiset/ns-minidumpapiset-minidump_exception_information">Learn more about this API from docs.microsoft.com</see>.</para>
    /// </remarks>
    internal struct MINIDUMP_EXCEPTION_INFORMATION : IEquatable<MINIDUMP_EXCEPTION_INFORMATION>
    {
        /// <summary>The identifier of the thread throwing the exception.</summary>
        internal uint ThreadId;

        /// <summary>
        /// <para>A pointer to an <a href = "https://docs.microsoft.com/windows/desktop/api/winnt/ns-winnt-exception_pointers">EXCEPTION_POINTERS</a> structure specifying a computer-independent description of the exception and the processor context at the time of the exception.</para>
        /// <para><see href = "https://docs.microsoft.com/windows/win32/api//minidumpapiset/ns-minidumpapiset-minidump_exception_information#members">Read more on docs.microsoft.com</see>.</para>
        /// </summary>
        internal nint ExceptionPointers;

        /// <summary>Determines where to get the memory regions pointed to by the <b>ExceptionPointers</b> member. Set to <b>TRUE</b> if the memory resides in the process being debugged (the target process of the debugger). Otherwise, set to <b>FALSE</b> if the memory resides in the address space of the calling program (the debugger process). If you are accessing local memory (in the calling process) you should not set this member to <b>TRUE</b>.</summary>
        internal BOOL ClientPointers;

        public bool Equals(MINIDUMP_EXCEPTION_INFORMATION other)
            => throw new NotImplementedException();

        public override bool Equals(object obj)
            => obj is MINIDUMP_EXCEPTION_INFORMATION minidumpExceptionInformation
               && this.Equals(minidumpExceptionInformation);

        public override int GetHashCode()
            => throw new NotImplementedException();
    }
}
```

But it resulted in it trying to generate that type anyway despite it being present in the project manually, as such it seems the only option is to have a version in the metadata that uses ``nint`` or ``IntPtr`` for that member instead. This is because it's safe for me to target AnyCPU as I just get that data directly from the runtime and I do not mess with it further.

**Comment by AArnott** [comment]
I took a quick look at your PR and it uses `<PackageReference Include="Microsoft.Windows.CsWin32" IsImplicitlyDefined="true" Version="*-*">`, so I can't clearly tell what version of CsWin32 you're using. But your struct declaration looks like it's got the right name and namespace, and doesn't use `partial`, so at least against 0.1.506-beta it appears it should suppress generation by CsWin32. What evidence leads you to say it's generating a redundant one? Especially since you say you're targeting AnyCPU, I wouldn't expect it to even try the first time, let alone generate a second one.

**Comment by AraHaan** [comment]
Change the first line in it's NativeMethods.txt from ``MINIDUMP_TYPE`` to ``MiniDumpWriteDump`` and then try to build, it should throw an error when building (since TreatWarningsAsErrors is enabled on specific projects and not others).

**Comment by AArnott** [comment]
I was already using MiniDumpWriteDump in NativeMethods.txt in my own test project and there are no build warnings or errors. 

> after removing the Pinvoke.DbgHelp.cs file.

What now? That's a generated file. How are you *removing* it? Removing generated code after it is generated is not supported.

**Comment by AraHaan** [comment]
Not generated, in my codebase I had to manually add one in that PR.

**Comment by jnm2** [comment]
Generated files usually have a `.g.cs` extension.

**Comment by AraHaan** [comment]
I have amended that PR with changes to show what I mean by that type not for some reason used in the code even when manually added to the project:
https://github.com/Elskom/Sdk/pull/190/checks?check_run_id=3146851352

**Comment by AArnott** [comment]
From the error message you're seeing, it looks like the problem is *not* that we're generating the struct twice, but rather that we're rejecting the generation of `MiniDumpWriteDump`. I suppose you expect it to work because you personally define the `struct` that leads that method to be considered arch-specific, but CsWin32 doesn't consider what you've already defined at that level. For example you might (in fact, you do!) define your struct in terms of other generated code. Your struct consumes `BOOL`, which is a generated type. When we emit any API, we have to be prepared to generate any API that your code doesn't, even skipping over one struct you define to define another struct that it depends on like BOOL. If we already know in advance that we cannot generate *everything* to support a given API, we skip the API. 
With effort we might be able to support what you're trying to do, but it's not supported today. Before we spent effort to support it, I'd want to know whether it's really legitimate to declare this struct in an AnyCPU assembly. If it is, I'd rather like to explore fixing the metadata so that you don't even have to use this workaround.

**Comment by AraHaan** [comment]
I personally think it’s legitimate as I only just retrieve the exception pointers from the runtime which the runtime itself returns it as an IntPtr and as such I think it should automatically decide for me wether to use the 32 bit exception pointers structure or the 64 bit one based on what the runtime returned.

**Comment by AraHaan** [comment]
I think I possibly found another workaround with https://github.com/Elskom/Sdk/pull/243/ but I am not entirely sure if that changes anything yet however.

**Comment by AArnott** [comment]
> I only just retrieve the exception pointers from the runtime which the runtime itself returns it as an IntPtr

I don't understand. Which runtime are you referring to? This `MINIDUMP_EXCEPTION_INFORMATION` struct is related to Windows rather than the .NET runtime, isn't it? Maybe you're referring to a similar struct found in the runtime though that the runtime uses when calling `MiniDumpWriteDump`, and that would be fine because `EXCEPTION_POINTERS*` *is* a pointer after all, so declaring the struct as `IntPtr` produces the same shape, just with less type information.

> I think it should automatically decide for me wether to use the 32 bit exception pointers structure or the 64 bit one based on what the runtime returned.

I'll wait to hear what runtime you're referring to to make sense of this comment. But I'll venture that the way these two struct definitions vary, it requires two declarations (assuming the attribute is required on one and forbidden on the other) and any method signature that requires the struct will have to refer to one or the other. So in fact CsWin32 *is* automatically generating the appropriate one based on target CPU, but at least as I'm thinking so far, that can only be a compile-time determination rather than a run-time one.

**Comment by AArnott** [comment]
@AaronRobinsonMSFT Can you comment on the importance of the distinction in this struct declaration going from x86 to either 64-bit architecture (arm64 or x64):

```diff
+[StructLayout(LayoutKind.Sequential, Pack = 4)]
+[SupportedArchitecture(Windows.Win32.Interop.Architecture.X64 | Windows.Win32.Interop.Architecture.Arm64)]
-[SupportedArchitecture(Architecture.X86)]
 public struct MINIDUMP_EXCEPTION_INFORMATION
 {
 	public uint ThreadId;

 	public unsafe EXCEPTION_POINTERS* ExceptionPointers;

 	public BOOL ClientPointers;
 }
```

In particular, is the Pack both required for correct 64-bit function and toxic for x86? Or could these two declarations be somehow expressed in harmony so that one "AnyCPU"-compatible declaration would work on any architecture?

**Comment by AaronRobinsonMSFT** [comment]
>In particular, is the Pack both required for correct 64-bit function and toxic for x86? Or could these two declarations be somehow expressed in harmony so that one "AnyCPU"-compatible declaration would work on any architecture?

@AArnott `Pack = 4` is fine for both architectures in this case. It is basically a no-op for x86 since the default Pack is 4 but is required for 64-bit. On 64-bit, without `Pack = 4` the `ExceptionPointers` field will be aligned on an 8 byte boundary and thus an extra 4 bytes inserted between `ThreadId` and `ExceptionPointers`. Unfortunately this does make the `ExceptionPointers` field unnaturally aligned for a 64-bit machine but that is how it is defined in the `DbgHelp.h`. The definition above should be compatible with AnyCPU.

>(I hate casts from 1 pointer type to another as it requires unsafe).

A quick note on the `unsafe` keyword in .NET Core 3.1 and .NET 5+. Using any API that returns or accepts an `IntPtr` and is inherently "unsafe". The `unsafe` keyword is a C# thing and has no impact on the generated code in any way so it really is a matter of preference. I personally prefer specifying the type precisely but there are many companies with constraints on putting `AllowUnsafeBlocks` in projects so occasionally it is easier to use `IntPtr` but it is all window dressing at this point in the .NET world.

**Comment by jnm2** [comment]
And I still say `IntPtr` is the real "unsafe." It's just as risky but also opts out of type checking.

**Comment by AArnott** [comment]
I've filed https://github.com/microsoft/win32metadata/issues/613 to track improving the metadata so that these structs can be generated in Any CPU.
