### ISSUE TITLE
Define all typedef "constants" as statics on the struct that declares their value type

### ISSUE THREAD

**Issue by jnm2** [microsoft/CsWin32#340]
These are nice to have when implementing callbacks that return HRESULT.

![image](https://user-images.githubusercontent.com/8040367/127228774-2454f0a8-053b-4664-bcf0-cd69e5ad1714.png)

In particular, as static members on HRESULT, the IDE will natively make it super easy to autocomplete them:

![image](https://user-images.githubusercontent.com/8040367/127228951-ec3d03f4-e697-40d2-be9a-2fe3cd2f98cb.png)

![image](https://user-images.githubusercontent.com/8040367/127228958-b59341c8-9547-47d9-b4a7-a54ee1bed3c6.png)

**Comment by AArnott** [comment]
The metadata defines `S_OK`, `E_FAIL` and many others as constants typed as `HRESULT`. 
One idea I've been playing with is making the C# projection lift all these constants as static fields on the structs that they define values for. This would mean that perhaps hundreds of E_ error constants would be defined on HRESULT, and you wouldn't have to ask for any of these constants explicitly in NativeMethods.txt since anything that would generate HRESULT would get all the constants too. Thoughts on that plan?

Alternatively yes we could just specially define a few (e.g. S_OK, S_FALSE, E_FAIL), but then we have to defend why we didn't get certain others that folks will want to see there.

**Comment by jnm2** [comment]
That plan sounds great to me!

**Comment by AArnott** [comment]
Ok then here's the overall proposal: move all constants that are typed as a typedef struct to be static members of those structs. So it doesn't just apply to HRESULT. 
@jnm2 Are you interested in sending a PR that does that?

**Comment by AArnott** [comment]
Generating _all_ constants into the typedef struct by default has a significant code generation perf and size toll. HRESULT would contain ~9000 constants. I'm dropping that part of the goal. Instead, you still have to request each constant (now with wildcards #544), but it will be generated into the typedef struct, when that struct isn't already found in a referenced assembly.
