### ISSUE TITLE
ImageList_Create should return a SafeHandle

### ISSUE THREAD

**Issue by jnm2** [microsoft/CsWin32#342]
All the `ImageList_` commands require a SafeHandle value which should come from ImageList_Create, but ImageList_Create returns `HIMAGELIST` instead.

### Context

- CsWin32 version: 0.1.506-beta
- Target Framework: net48
- `LangVersion`: 9

**Comment by AArnott** [comment]
I don't repro this. With that same CsWin32 version, `ImageList_Create` is generated twice, with the friendly overload returning a safe handle:

```cs
		[SupportedOSPlatform("windows6.0.6000")]
		internal static unsafe ImageList_DestroySafeHandle ImageList_Create_SafeHandle(int cx, int cy, uint flags, int cInitial, int cGrow)
		{
win32.UI.Controls.HIMAGELIST __result = PInvoke.ImageList_Create(cx, cy, flags, cInitial, cGrow);
			return new ImageList_DestroySafeHandle(__result,ownsHandle: true);
		}

		[DllImport("ComCtl32", ExactSpelling = true)]
[DefaultDllImportSearchPaths(DllImportSearchPath.System32)][SupportedOSPlatform("windows6.0.6000")]
		internal static extern win32.UI.Controls.HIMAGELIST ImageList_Create(int cx, int cy, uint flags, int cInitial, int cGrow);
```

Note however that since the friendly overload signature *only* differs from the `extern` method by return type that we had (for C#'s sake) to give it a special name rather than create another overload. All such cases add a `_SafeHandle` suffix to the method name.
