### ISSUE TITLE
Structures without postfixes try wide variant if not found in metadata

### ISSUE THREAD

**Issue by StephenCleary** [microsoft/CsWin32#360]
Just using this project for the first time. I wanted to generate `STARTUPINFOEX` for use with `CreateProcess`.

In a new .NET Core 5 class library, I can specify `CreateProcess` in `NativeMethods.txt`, but I can't specify `STARTUPINFOEX`. After research, it turns out the metadata does have that structure, but with a `W` postfix. Specifying `STARTUPINFOEXW` in `NativeMethods.txt` does work.

CsWin32 will auto-append `W` to `CreateProcess`, but doesn't do it for `STARTUPINFOEX`. I assume CsWin32 does this for methods but not structures.

Is it possible to append `W` for structures automatically? If not, could you describe why not (just for my curiosity) and add a brief line to the getting-started docs (for future devs)?

**Comment by AArnott** [comment]
I don't recall a particular reason we couldn't do it for structures as well.

**Comment by AArnott** [comment]
`CreateProcess` actually generates a method called `CreateProcess`, although it binds to a `CreateProcessW` native method. So accepting `CreateProcess` as input doesn't produce a usability issue because you ask for X and you get X. 
However for structs, which are _types_ rather than methods and can be referenced elsewhere, we figured we should keep the original suffix on the name. Accepting `STARTUPINFOEX` as input but generating `STARTUPINFOEXW` may hurt usability.

Instead, I'm leaning with what we currently have, as described in #196, which at least helps folks discover and correct the problem:

> warning PInvoke001: Method, type or constant "STARTUPINFOEX" not found. Did you mean "STARTUPINFOEXA" or "STARTUPINFOEXW"?
