### ISSUE TITLE
Bumping version of MessagePack breaks source generation inside VisualStudio

### ISSUE THREAD

**Issue by pziezio** [microsoft/CsWin32#371]
## Actual behavior

f25bc2d updated MessagePack version from `2.2.x` to `2.3.x` which [has some breaking changes](https://github.com/neuecc/MessagePack-CSharp/releases/tag/v2.3.75) regarding serialization of `Dictionary<>`.

Simple example fails to generate sources inside VisualStudio:
`CSC : warning CS8785: Generator 'SourceGenerator' failed to generate source. It will not contribute to the output and compilation errors may occur as a result. Exception was of type 'MessagePackSerializationException' with message 'Failed to deserialize System.Collections.Generic.Dictionary2[[System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[Microsoft.Windows.SDK.Win32Docs.ApiDetails, Microsoft.Windows.SDK.Win32Docs, Version=0.1.4.39555, Culture=neutral, PublicKeyToken=7c40c7c34b1fcfe1]] value.`

Compiling project from command line with `dotnet build` works without problem - that's probably why all automatic tests also works.
I've recompiled CsWin32 with MessagePack version downgraded to `2.2.x` and it works again.

## Repro steps

1. `NativeMethods.txt` content:
```
CreateFile
```

2. Empty console project with `using Windows.Win32;`

### Context

- CsWin32 version: 0.1.539-beta
- Target Framework: net5.0
- VisualStudio: 2019 and 2022

**Comment by pziezio** [comment]
When I tried to debug some tests the inner exception says `"Could not load file or assembly 'MessagePack.Annotations, Version=2.3.0.0, Culture=neutral, PublicKeyToken=b4a0369545f0a1be' or one of its dependencies. The system cannot find the file specified."`.

But that happens only in `net472` tests.
`\bin\Microsoft.Windows.CsWin32.Tests\Debug\net472` folder does not contain `MessagePack.Annotations.dll` file.

Since I create a new `net5.0` project I don't understand how that relates. Newly created project correctly references `CsWin32` and `MessagePack` and `MessagePack.Annotations` as it's dependencies.

![messagepack_exception](https://user-images.githubusercontent.com/3835685/130832648-0f003f9c-181b-40c5-b735-54854f5e8c4d.png)

**Comment by AArnott** [comment]
The two issues reported (test failure, failure in real project) were actually two different failures. The test failure was not due to the upgrade. But as the real project failure _is_ due to the upgrade, I have to roll back the upgrade.

The issue is the win32metadata repo ships an assembly that depends on MessagePack.Annotations 2.2.0.0. If we ship 2.3.0.0 of that assembly, then the .NET Framework-based C# compiler does not see these as equal and throws an exception. Roslyn does not provide analyzers a way to supply binding redirects, so we simply have to exactly match the version in win32metadata.
