### ISSUE TITLE
Missing constants of Win32Metadata.Shell-module

### ISSUE THREAD

**Issue by AliveDevil** [microsoft/CsWin32#393]
## Actual behavior

The metadata project contains constants for [KNOWNFOLDERID](https://docs.microsoft.com/en-us/windows/win32/shell/knownfolderid), but I cannot get them to generate.
Even `Shell32.*` does not generate them (in fact: `Shell32.*` does not generate _any_ constants, except explicitely mentioned ones).

## Expected behavior

Expose `FOLDERID_*` as static GUID field (like `CLSID_MyComputer`)

## Repro steps

1. `NativeMethods.txt` content:
```
FOLDERID_ComputerFolder
```

### Context

- CsWin32 version: `0.1.560-beta`
- Target Framework: net5.0-windows10.0.17763.0

**Comment by AArnott** [comment]
> The metadata project contains constants for KNOWNFOLDERID

I see no such constants in the metadata:
![image](https://user-images.githubusercontent.com/3548/133497468-190ce801-1c64-40e9-9854-c6fbde28c0ac.png)

Nor [in the source code](https://github.com/microsoft/win32metadata/search?q=KNOWNFOLDERID).

Where do you see it? If it's really in the metadata but CsWin32 won't generate them, then this issue is in the right place.
But if it's missing from the metadata, I'll transfer this issue to the metadata repo.

**Comment by AliveDevil** [comment]
They aren't named after KnownFolderId, unfortunately.
They are prefixed with `FOLDERID_`:

![image](https://user-images.githubusercontent.com/734738/133498252-9651f414-833e-453e-897c-a8723d315a97.png)

**Comment by AArnott** [comment]
Ah yes of course.

But that works for me too:

![image](https://user-images.githubusercontent.com/3548/133498738-b085ce21-32b5-4ec1-a7c4-20c185ae4b75.png)

**Comment by AliveDevil** [comment]
Well … eventually I got some weird Unicode characters as well in there, due to copy&pasting from some website, which contains this weird soft-hyphens. Tried again on another machine and it works here as well now. Mysteries.
