### ISSUE TITLE
ValueTask-based methods for Overlapped I/O

### ISSUE THREAD

**Issue by qmfrederik** [microsoft/CsWin32#424]
I'm trying to determine whether we can/should migrate from dotnet/pinvoke to dotnet/cswin32. One of my use cases include overlapped I/O (for example, `DeviceIoControl` and `WinUsb_ReadPipe`).

Are there any plans to have CsWin32 generate ValueTask-based methods which wrap around Win32 APIs which perform overlapped I/O? For example, in dotnet/pinvoke, we have:

```csharp
public static unsafe ValueTask<uint> DeviceIoControlAsync<TInput, TOutput>(
    SafeObjectHandle hDevice,
    uint dwIoControlCode,
    Memory<TInput> inBuffer,
    Memory<TOutput> outBuffer,
    CancellationToken cancellationToken)
    where TInput : unmanaged
    where TOutput : unmanaged
```

and it would be great if CsWin32 could generate a similar helper method.

**Comment by AArnott** [comment]
I think that's a fine idea. I'd definitely like it to be template-based (as in, the `templates` directory) so that the custom C# can be read/written more conveniently than SyntaxFactory based. But we may need to improve it so the templates can effectively do `#if` but have the generator interpret and add/remove the code before it's emitted to the user's project, presumably based on our own define symbols so we're not reliant on the project. For example maybe an expression could be `#if SPAN`. 

Another consideration would be how to trigger these special templates. My first guess would be when we generate the overlapped I/O p/invoke, we "throw in" the extra higher level APIs. 

Another consideration is that once triggered by some API, the templates may require *more* APIs. Right now I don't think CsWin32 supports recognizing when the templates require more APIs, so we'd need a system to figure that out. Maybe some sort of manifest where additional metadata per template could be included.

Given these possibly unexpected "bonuses", we might also have a json option to turn the behavior off. I think on by default is fine, if our design is good enough to not typically cause problems.

Thoughts? Let's get the design hashed out here before any PR.

**Comment by qmfrederik** [comment]
> Another consideration would be how to trigger these special templates. 

I assume a good indication is the presence of a parameter of type `LPOVERLAPPED`, like in `DeviceIoControl`:

```c
BOOL DeviceIoControl(
  HANDLE       hDevice,
  DWORD        dwIoControlCode,
  LPVOID       lpInBuffer,
  DWORD        nInBufferSize,
  LPVOID       lpOutBuffer,
  DWORD        nOutBufferSize,
  LPDWORD      lpBytesReturned,
  LPOVERLAPPED lpOverlapped
);
```

To generate an async overload, you need at least the following information:
- This method operates on two buffers (`lpInBuffer` and `lpOutBuffer`). Other methods (eg `ReadFile` and `WriteFile`) only operate on a single buffer.
- In this case, the first buffer is read-only (i.e. `ReadOnlyMemory<byte>`).
- The name of the function to call to get the overlapped result (e.g. `WinUsb_GetOverlappedResult` for WinUsb and `GetOverlappedResult` for most other Win32 APIs).

Is that metadata available, or would we need an alternative mechanism (a heuristic, a json file,...) to encode that?

Thinking about this a bit more, we may end up with 3 templates:
- A template for I/O functions which take an input buffer (e.g. WriteFile)
- A template for I/O functions which take an output buffer (e.g. ReadFile)
- A template for I/O functions which take both an input and output buffer (DeviceIoControl).
where each template takes a couple of parameters (name of the method and name of the result method being the ones that come to mind right now).

**Comment by AArnott** [comment]
Whoa, you mean to dynamically generate the async methods based on patterns in the metadata, instead of as pre-written c#? Interesting.

I don't think we're going to get the metadata to include such semantic usage information as that, but I can bring it up with the team to find out. Otherwise, yes a data file of some kind seems appropriate. 

TBH I haven't studied the async implementations in the dotnet/pinvoke repo since they were originally written. I'll need to refresh my memory on that before being especially helpful on this. In the meantime though I welcome you writing out ideas/proposals.

**Comment by qmfrederik** [comment]
I think most of the async methods will be very similar, and there would be some benefit in using a template to generate these methods. If not, it's likely you'll end up with various, slightly divergent implementations over time.

It's probably fine to keep the metadata in a .json file which is manually maintained. There are couple of templating engines (like mustache) which could do the job.

I'll do some experiments over in dotnet/pinvoke (I'm more familiar with that codebase). Let me see if I can come up with a templating mechanism to generate the few async wrappers we have there. We can probably extract some learnings from that exercise, which we can probably project into CsWin32.

**Comment by AArnott** [comment]
@qmfrederik I'm going to close this issue as part of an overall review of active issues to help us focus our efforts. What you propose is still interesting though, so if you ever get back around to it, ping here and we can reactivate as appropriate.
