### ISSUE TITLE
SHAppBarMessage isn't generated

### ISSUE THREAD

**Issue by dongle-the-gadget** [microsoft/CsWin32#505]
## Actual behavior

`Shell32.SHAppBarMessage` isn't generated by the CsWin32 generator, even though [it is documented](https://docs.microsoft.com/en-us/windows/win32/api/shellapi/nf-shellapi-shappbarmessage).

## Expected behavior

`Shell32.SHAppBarMessage` should be generated.

## Repro steps

`NativeMethods.txt`:
```
SHAppBarMessage
```

### Context

- CsWin32 version: `0.1.635-beta`
- Target Framework: `net6.0-windows`

**Comment by AArnott** [comment]
I cannot repro this. It generates fine for me, using the version you tried:
![image](https://user-images.githubusercontent.com/3548/154107766-6c768b19-6afe-4642-9961-fb0dfc98882c.png)

Are you sure you don't have invisible characters in your NativeMethods.txt file that could be corrupting the method name? We get that sometimes when copy/pasting API names from online documentation.

**Comment by dongle-the-gadget** [comment]
oh, let me try it again.

**Comment by dongle-the-gadget** [comment]
@AArnott, here's my repro
<img width="1128" alt="image" src="https://user-images.githubusercontent.com/29563098/154202157-8d7ac4c5-9928-4a15-a250-74a0dce3b024.png">

I also tried copying the whole file into a Unicode inspector, and it didn't detect any strange characters
<img width="709" alt="image" src="https://user-images.githubusercontent.com/29563098/154202310-a6179d22-65b1-491c-94c1-f92b96230739.png">

**Comment by riverar** [comment]
Open your Error List and you'll probably see:
```
NativeMethods.txt(1,1,1,16): warning PInvoke005: This API is only available when targeting a specific CPU architecture. AnyCPU cannot generate this API.
```

**Comment by dongle-the-gadget** [comment]
> Open your Error List and you'll probably see:
> 
> ```
> NativeMethods.txt(1,1,1,16): warning PInvoke005:
> This API is only available when targeting a specific CPU architecture. AnyCPU cannot generate this API.
> ```

I needed to build the project in order to see it though, but changing the architecture did resolve the bug.

**Comment by AArnott** [comment]
I wish the roslyn source generation-produced warnings would appear in the error list to make this more discoverable. They have [an open bug](https://github.com/dotnet/roslyn/issues/49531) on them to do that. Please upvote it.

As for an error vs. a warning, we use the same rationalization that bad references have: failure to generate an API (or reference an assembly) is only fatal if you need it, in which case the need will be the error, and the original cause will be a warning.

**Comment by AArnott** [comment]
> `APPBARDATA` is defined for all supported architectures

The metadata defines this struct twice -- once for x86 and once for amd64/arm64. This generally means we can't generate just one for AnyCPU and expect it to work everywhere. The only difference in this case is that x86 sets the Pack size to 1. Since 4 is the default on x86, I expect that's important.

**Comment by riverar** [comment]
> The metadata defines this struct twice -- once for x86 and once for amd64/arm64. This generally means we can't generate just one for AnyCPU and expect it to work everywhere. The only difference in this case is that x86 sets the Pack size to 1. Since 4 is the default on x86, I expect that's important.

I'm not an AnyCPU user or fan, but I think there may be an opportunity where CsWin32 could perhaps detect all the struct members are the same and then generate/encapsulate all architecture-specific structs and expose a generic for AnyCPU usage. But maybe that's too much work for little gain.

**Comment by AArnott** [comment]
If the facade struct itself didn't have any fields, only properties accessors, it could be done without an extra data copy step. But downsides:
1. The user would not be able to pass around pointers to the structs, which interop often requires or lends towards.
2. The user couldn't pass the properties in as `ref`/`out` parameters to methods like fields can.
3. And ya as you say, this would be quite expensive.

**Comment by HavenDV** [comment]
What if you do it the way it is implemented in WinUIEx?
https://github.com/dotMorten/WinUIEx/blob/main/src/WinUIEx/Interop.cs

This will allow additional checks to be made further and the library to be distributed as AnyCPU.

**Comment by AArnott** [comment]
@havendv it sounds like you're advocating for always generating *both* structs, and methods for each, and letting the app author decide which to call at runtime. Yes, that would work in this simple case. But as the CsWin32 generator has to work for the general case (i.e. apply the rule equally across the whole Win32 surface), consider APIs that would match this pattern, but where the struct is used as a field by other structs. And maybe there are delegates that take these structs as parameters, and other methods that take the delegate, or structs that use the delegate as a field. It gets quite crazy very quickly to consider the full impact. And forking all those many APIs with 32 and 64 suffixes actually can make writing code against it much harder, because you have no type equivalence anywhere and every access to these types requires code written twice.
Compare that with a simple world of just compiling for x86 and x64 separately, you have perfect type equivalence (you have only one type) and you don't have to duplicate any code. 

Ya, I get that AnyCPU is "nice", but in the world of interop, it's often something you have to sacrifice sooner or later anyway.
