### ISSUE TITLE
EVENT_TRACE_PROPERTIES struct isn't properly defined

### ISSUE THREAD

**Issue by palenshus** [microsoft/CsWin32#526]
## Actual behavior

The [EVENT_TRACE_PROPERTIES](https://docs.microsoft.com/en-us/windows/win32/api/evntrace/ns-evntrace-event_trace_properties) struct is missing the offset-strings at the end, see comments in the [Remarks section](https://docs.microsoft.com/en-us/windows/win32/api/evntrace/ns-evntrace-event_trace_properties#remarks)

## Expected behavior

If you have an existing trace session, this should succeed:

```lang-cs
var dummyProp = new EVENT_TRACE_PROPERTIES();
dummyProp.Wnode.Guid = new Guid();
dummyProp.Wnode.Flags = PInvoke.WNODE_FLAG_TRACED_GUID;
dummyProp.Wnode.BufferSize = (uint)Marshal.SizeOf(typeof(EVENT_TRACE_PROPERTIES));

uint retVal = PInvoke.ControlTrace(sessionHandle, sessionName, ref dummyProp, EVENT_TRACE_CONTROL.EVENT_TRACE_CONTROL_STOP);
```

## Repro steps

1. `NativeMethods.txt` content:
```
ControlTrace
WNODE_FLAG_TRACED_GUID
```

2. `NativeMethods.json` content (if present):
```json
```

3. Any of your own code that should be shared?

I don't have a trivial repro, there's a lot of code to create a session. However, I found another implementation that adds some string buffers on to the end of the struct definition:

```lang-cs
...
            private uint LogFileNameOffset;
            private uint LoggerNameOffset;

            const int STR_ARR_SIZE = 1024;

            [MarshalAs(UnmanagedType.ByValArray, SizeConst = STR_ARR_SIZE)]
            internal char[] loggerNameChArr;
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = STR_ARR_SIZE)]
            internal char[] logFileNameChArr;
```

And that one seems to work when I call the same ControlTrace command.

### Context

- CsWin32 version: 0.1.635-beta
- Target Framework: .NET Framework 4.8

**Comment by AArnott** [comment]
I tried this with CsWin32 0.2.46-beta and the last fields in the struct match the last fields in the metadata, and the docs. I believe that means it's correct.
From your description though and the Remarks section of the doc, it sounds like this struct is a special case in that it doesn't fully encapsulate the memory you must allocate. This must be a tricky bit of memory to initialize in C as well. This same procedure should work in C#, and making it easier is beyond the scope of both the metadata and CsWin32. You should expect to typically be required to do your own memory management in C# with these generated APIs just like in C. The only exceptions to this are very common cases that are easy to get right in a general way. It turns out that encompasses a bunch of APIs, leaving this one out in the cold. But that's the way it's gotta be because there are just too many APIs with special considerations to custom write code in the generator for.
CsWin32 generated code is not meant to be easy to use like the BCL. Higher level libraries built on CsWin32 are encouraged and a great way to go.
