### ISSUE TITLE
Plans to migrate to LibraryImportAttribute?

### ISSUE THREAD

**Issue by elachlan** [microsoft/CsWin32#593]
Are there plans to migrate to [LibraryImportAttribute](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.libraryimportattribute?view=net-7.0) for .NET7+?

**Comment by AArnott** [comment]
This is the first I've heard about the attribute. I've heard about the source generator that avoids relying on the .NET runtime for interop code. CsWin32 is actually pretty close to this already for `extern` methods because if you turn off marshaling (a CsWin32 setting) we emit blittable, non-marshaled extern methods, and replace COM interfaces with blittable structs. It's not the most friendly API, but it's a start toward this if folks really want this.

**Comment by elachlan** [comment]
Thanks for the reply!

What about function pointers? Would they work/make sense in CSWin32 or are they already implemented?
https://github.com/dotnet/winforms/issues/4135

eg:
https://github.com/dotnet/winforms/pull/4003

**Comment by AArnott** [comment]
Yes, CsWin32 already generated function pointers where needed.

**Comment by alexrp** [comment]
It's worth noting that CsWin32's support for disabling marshalling won't actually be usable with [`DisableRuntimeMarshallingAttribute`](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.compilerservices.disableruntimemarshallingattribute) yet because of `SetLastError`: https://docs.microsoft.com/en-us/dotnet/standard/native-interop/disabled-marshalling#disabled-features

`LibraryImportAttribute` supports generating appropriate code for `SetLastError`, so that's a point in favor of using it.

**Comment by AArnott** [comment]
Given Roslyn doesn't support chaining source generators. CsWin32 already does a significant amount of work to avoid relying on .NET marshaling already, and has just a bit more to do (#600). 
If we need more from LibraryImport, we'll just have to borrow code (or even the dll) from that source generator.
