### ISSUE TITLE
Consider emitting GeneratedCodeAttribute on all generated types

### ISSUE THREAD

**Issue by AArnott** [microsoft/CsWin32#594]
See [the docs](https://docs.microsoft.com/en-us/dotnet/api/system.codedom.compiler.generatedcodeattribute?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(System.CodeDom.Compiler.GeneratedCodeAttribute)%3Bk(SolutionItemsProject)%3Bk(DevLang-csharp)%26rd%3Dtrue&view=net-6.0) for the attribute. The `LibraryImportAttribute` source generator emits code that uses this. It seems like a possibly good idea.

**Comment by elachlan** [comment]
The GeneratedCodeAttribute doesn't have `AllowMultiple`, so it can only be applied to a single file of a partial class/struct. This seems super weird since I would imagine you want to tag each code file with the attribute. 
https://docs.microsoft.com/en-us/dotnet/api/system.codedom.compiler.generatedcodeattribute?view=net-6.0
