### ISSUE TITLE
Documentation Improvements around Customizing generated code

### ISSUE THREAD

**Issue by elachlan** [microsoft/CsWin32#606]
The documentation does not outline exactly how to split the NativeMethods.txt into multiple files. It just says that it is possible.

Additionally, the documentation lists possible ways to customize generated code, but again doesn't list the appropriate settings for the `NativeMethods.json`.

**Comment by elachlan** [comment]
For the `NativeMethods.txt`, do you just name them like `*.NativeMethods.txt` or do the files need to be named all `NativeMethods.txt` but in separate directories?

**Comment by AArnott** [comment]
We don't recommend splitting NativeMethods.txt up. At least, I haven't come across any scenario where it would be beneficial. I heard someone suggest a couple weeks ago that perhaps one in each feature directory of a library would make sense, where the APIs used by that feature would be listed. But that's not really sustainable because there is no enforcement, and it would be a lot of extra bookkeeping on the part of the consumer to try to avoid using APIs that weren't asked for in their local file.
The reason we support multiple files is for Shared Project scenarios, where legitimately shared code requires p/invokes and should carry its own NativeMethods.txt file so that anyone who consumes the Shared Project will automatically generate the APIs it needs.

But yes, we could document it better. 

The nativemethods.json isn't documented much except to include the `$schema` field, which is all you need in VS to get Intellisense in the file with docs that teach you what is available and what it does. Have you found that to be insufficient?

**Comment by elachlan** [comment]
Thanks, that all makes sense. Possibly append the multiple `NativeMethods.txt` section with your recommendation above?

In Winforms, the idea was to have a NativeMethods.txt file in each interop dll directory. I imagine the txt file will end up being several thousands of lines long if it was centralized. Is the idea of breaking the files up per library not a good idea?

**Comment by AArnott** [comment]
> the idea was to have a NativeMethods.txt file in each interop dll directory

Would you still have a whole directory per each interop dll if CsWin32 was generating most of the code? Ideally, you have little or no interop to write yourself, unless you're writing a higher level set of classes.

**Comment by elachlan** [comment]
The winforms team looks like it will go with a single `NativeMethods.txt`.

That being said, In Winforms `IHandle` is used on forms/controls/etc to provide access to the objects Handle. Winforms then has code like this:
```csharp
public unsafe static BOOL ValidateRect(IHandle hWnd, RECT* lpRect)
{
    BOOL result = ValidateRect(hWnd.Handle, lpRect);
    GC.KeepAlive(hWnd);
    return result;
}
```
I brought this up in https://github.com/microsoft/CsWin32/issues/602. It was suggested there was an alternative way using a struct.

I suspect the winforms team will want to keep this structure. So the per interop dll folders might end up staying. 

If CsWin32 provided a similar interface and methods, then I'd image the folders wouldn't be needed.

**Comment by AArnott** [comment]
Thanks. We are still reviewing the IHandle proposal. Not sure what CsWin32 will do to help with that yet.
