### ISSUE TITLE
Source Generator not installed for packages.config projects

### ISSUE THREAD

**Issue by riverar** [microsoft/CsWin32#62]
Repro steps:
1. Start Visual Studio 2019 (16.8.3)
2. File > New > Project > Console App (.NET Framework), select framework `.NET Framework 4.8`, then click the Create button
3. Add `Microsoft.Windows.CsWin32` nuget prerelease package
4. Add `NativeMethods.txt` file, with single line containing `CreateFileW`
5. Rebuild
6. Observe parent Microsoft.Windows namespace does not exist per documentation

**Comment by riverar** [comment]
Update: `C# 9.0` requires .NET 5, so this will never work. The README is incorrect as it states (emphasis mine):
> Source Generators require C# 9, which comes with the .NET 5 SDK **or Visual Studio 2019 Update 8 (16.8)**.

**Comment by Micke3rd** [comment]
> The README is a bit misleading as it states (emphasis mine):
> > Source Generators require C# 9, which comes with the .NET 5 SDK **or Visual Studio 2019 Update 8 (16.8)**.

The README isn't misleading, you dont read OR conditions correct.

**Comment by AArnott** [comment]
@riverar, this project does indeed support projects targeting .NET Framework. You only need to use the C# 9 version of the compiler. That compiler ships both with VS 2019.8 and the .NET 5 SDK. But *targeting* .NET 5 is *not* necessary.

Following your repro steps, I hit the same symptom you did. But only when my IDE/project was configured to use packages.config. If I removed the packages from the project and changed my IDE to prefer PackageReference, then reinstalled the "Microsoft.Windows.CsWin32" package, it worked.

So, I'm going to reactivate and retitle your issue to track that this doesn't work with packages.config and will investigate whether we can fix that. I also filed https://github.com/microsoft/win32metadata/issues/180 to track another minor issue I saw with packages.config that must be fixed in the metadata.

Thank you for your report. In the meantime, can you switch from packages.config to PackageReference? It's a much better world anyway 😉.

**Comment by riverar** [comment]
@AArnott Thanks Andrew. Definitely confused here because according to Microsoft elsewhere, C# 9 requires .NET 5. 

> C# 9.0 is supported on .NET 5. For more information, see C# language versioning.
https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-9

**Comment by AArnott** [comment]
You're making the understandable mistake of confusing compiler versions with language versions. Using the C# 9 *language* version is only officially supported on the .NET 5 runtime, it is true. However this source generator only requires the C# 9 version of the compiler. Your project can still set C# 7.3 or 8 as its `LangVersion` and the source generator will still run, and you'd still be on a supported path.

That said, the source generator may generate syntax that only the C# 9 *language version* will parse. For example, we do generate function pointers at times, and that requires the C# 9 language version. But you may not even need to generate any function pointers, and you'd be fine with a lesser language version. 
Or you could even go ahead and use C# 9 language version for your .NET Framework targeted projects (as I do for many of my projects). In my experience it still works great -- just avoid the features [listed](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/configure-language-version) as requiring a newer runtime than you are targeting.

**Comment by riverar** [comment]
`csc /?` produces:
```
Microsoft (R) Visual C# Compiler version 3.9.0-1.20521.14 (182c1e33)
Copyright (C) Microsoft Corporation. All rights reserved.
```

The README states:
> Source Generators require C# 9, which comes with the .NET 5 SDK or Visual Studio 2019 Update 8 (16.8).

How would users know if they have the C# 9 compiler?

**Comment by Micke3rd** [comment]
> You're making the understandable mistake of confusing compiler versions with language versions

He doesn't. C# 9 is the name of a language.

**Comment by AArnott** [comment]
@micke3rd Fair enough. I'll revise my wording going forward and update the published docs on this repo to be more clear.
