### ISSUE TITLE
`[In, Out] char*` parameter MUST NOT generate `string` as a friendly overload

### ISSUE THREAD

**Issue by riverar** [microsoft/CsWin32#64]
This API takes in a `LPWStr`, scribbles a NUL on it, and returns the numeric component.

Shlwapi!PathParseIconLocationW per headers is defined as such:
```cpp
int PathParseIconLocationW(
  LPWSTR pszIconFile
);
```

Win32 metadata describes it as such:
```csharp
[DllImport("SHLWAPI", ExactSpelling = true)]
public unsafe static extern int PathParseIconLocationW(
  [In] [Out] [NativeTypeInfo(UnmanagedType.LPWStr)] ushort* pszIconFile);
```

CsWin32 generated:
```csharp
[DllImport("ShlwApi", ExactSpelling = true, EntryPoint = "PathParseIconLocationW")]
internal static extern unsafe int PathParseIconLocation([In, Out] char *pszIconFile);
// ...
internal static unsafe int PathParseIconLocation(string pszIconFile)
{
    fixed (char *pszIconFileLocal = pszIconFile)
    {
        return PInvoke.PathParseIconLocation(pszIconFileLocal);
    }
}
```

A simpler, safer approach:
```csharp
[DllImport("shlwapi.dll", ExactSpelling = true, PreserveSig = true)]
internal static extern int PathParseIconLocationW(
    [MarshalAs(UnmanagedType.LPWStr)]
    StringBuilder pszIconFile);
```

We might be able to get away with using StringBuilder in all cases where metadata describes a parameter as `[In, Out] char *`. But I haven't had my coffee yet to say so definitively.

This is also a great example of how these wrappers dangerously hide the side effects of `unsafe`, in this case mutating what was expected to be an immutable string.

**Comment by AArnott** [comment]
> in this case mutating what was expected to be an immutable string.

Yikes! This is definitely a must-fix.

**Comment by tannergooding** [comment]
This should apply to any `[Out] string` (anything documented as mutating the string)

**Comment by riverar** [comment]
@AArnott How do I consume the bleeding edge to test this fix? There was talk about [Out] strings but that isn't applicable to this API so want to take the fix for a spin.

**Comment by AArnott** [comment]
@riverar Testing this would be great. Thank you. 

The readme includes the link and instructions to consume our daily builds. You'll want to look for a package version of 0.1.372 or later to test this fix. The daily build that includes this change will come out in about 5 hours.

**Comment by riverar** [comment]
@aarnott Well I verified the string overload is gone, so bug fixed I suppose. But now there's just an incredibly difficult to use PWSTR in its place. 😑

**Comment by riverar** [comment]
I guess the scenario is now:

```csharp
var notImmutableIconLocation = "icon.dll,1";
unsafe
{
    fixed (char* ptr = notImmutableIconLocation)
    {
        PInvoke.PathParseIconLocation(ptr);
    }
}
```

And the user just has to remember `notImmutableIconLocation` is not an immutable string? Is there another pattern I'm missing here?

**Comment by jnm2** [comment]
I believe it is never safe to mutate a string because the runtime interns (deduplicates) string instances and IIRC there are plans in the works to make even `new string` overloads return existing pooled instances.

**Comment by AArnott** [comment]
> the runtime interns (deduplicates) string instances

I've never heard that it does. And some substantial libraries I know go to lengths to intern strings themselves which wouldn't be necessary if the CLR did it. The BCL itself has a public interning method.
@jnm2 If you have links to share, I'd love to learn what is planned around `new string` that you mention.

@riverar no, don't pass `string` into a mutable function. That defeats the point of the change. What @jnm2 suggests is counter to the docs, which require a string of `MAX_PATH` in length in this case. Here is what I would do:

```cs
private unsafe (string Path, int Index) PathParseIconLocation(string pathAndIndex)
{
    const int MAX_PATH = 260;
    Span<char> szIconFile = stackalloc char[MAX_PATH];
    pathAndIndex.AsSpan().CopyTo(szIconFile);
    fixed (char* pszIconFile = szIconFile)
    {
        int index = PInvoke.PathParseIconLocation(pszIconFile);
        return (new string(pszIconFile), index);
    }
}
```

**Comment by AArnott** [comment]
If the friendly overload accepted a `StringBuilder`, the code could look like this:

```cs
private unsafe (string Path, int Index) PathParseIconLocation(string pathAndIndex)
{
    const int MAX_PATH = 260;
    var szIconFile = new StringBuilder(pathAndIndex, MAX_PATH);
    int index = PInvoke.PathParseIconLocation(szIconFile);
    return (szIconFile.ToString(), index);
}
```

That would incur an extra allocation, but that's a common cost of the friendly overloads, so probably an ok cost.

**Comment by AArnott** [comment]
See #144

**Comment by jnm2** [comment]
> If you have links to share, I'd love to learn what is planned around new string that you mention.

https://github.com/dotnet/runtime/blob/master/docs/design/features/StringDeduplication.md

**Comment by riverar** [comment]
So we've come full circle to my original report. :smile:

Opinion: I'm also starting to wonder if all this hoop jumping truly helps anyone. Without a documented problem and supporting data, it really feels like we are micro-optimizing perf over language safety features and C# developer sanity.

**Comment by jnm2** [comment]
I am 100% in favor of `Span<char>` for this because it allows passing `char[]` or `Memory<char>` or, if you use `unsafe`, a `stackalloc` span.

**Comment by AArnott** [comment]
`stackalloc` assigned to span does not require `unsafe`. And it is very tempting to add `Span<char>` for mutable strings. The problem is that span implies a length, but where native code does not take a length, that implication is misleading. Suppose for example you provide a `Span<char>` with a length of 5, whose content is "hello". Sound good so far? Well, it's bad, because the native code that didn't take a length assumes a null-terminated string, and there is no justification in as assumption that two null  bytes (a UTF-16 null character) follows that span in memory, which would lead to malfunction in the native code.

So where the native code takes a pointer and a length we can and do take `Span<T>` or `ReadOnlySpan<T>`. Otherwise we take pointers (or with #144, a `StringBuilder`) so that null termination requirements are more obvious.

**Comment by AArnott** [comment]
@jnm2 Let's follow up on the span discussion over at #144

**Comment by tannergooding** [comment]
> I've seen warnings in various discussion places (maybe by Tanner and others if I remember right) that made me realize my code that mutates new string instances could break in the future.

Right. The runtime has investigated automatic string interning and reserves the right to enable it in any release.
Strings are immutable, by design, and attempting to mutate them (particularly literals) can result in weird behaviors.

My favorite example is:
```csharp
using System;

PseudoNativeCall("Hello, World!");
Console.WriteLine("Hello, World!");

unsafe static void PseudoNativeCall(string s)
{
    fixed (char* c = s)
    {
        c[0] = 'J';
    }
}
```

which prints `Jello, World!`.

Likewise, there is no guarantee the mutation will succeed. The runtime is free to place literals and the IL, etc in read only memory in which case mutating it may result in an AccessViolationException.
In some cases (such as on more locked down platforms) this may even be the default scenario. Apple Silicon, the ARM64 variant, for example requires that executable code not be writable and so we had to add such support and begin enforcing it for that platform.

If you really must mutate a string, such as for efficient allocation, we provide [String.Create](https://docs.microsoft.com/en-us/dotnet/api/system.string.create?view=net-5.0) which provides a `SpanAction` callback allowing you to safely mutate before the memory becomes "immutable" and is open to being placed in readonly memory or subject to string interning.

**Comment by tannergooding** [comment]
For reference, we also block `[Out] string` (which is distinct from `out string` or `[Out] out string`) as of recent .NET Core: https://github.com/dotnet/coreclr/pull/21513

https://docs.microsoft.com/en-us/dotnet/standard/native-interop/best-practices should be up to date with the modern best practices
