### ISSUE TITLE
IDataObject methods should return HRESULT

### ISSUE THREAD

**Issue by RachelDavids** [microsoft/CsWin32#663]
## Actual behavior

generated code has signature with void

## Expected behavior

According to [MSDN](https://docs.microsoft.com/en-gb/windows/win32/api/objidl/nn-objidl-idataobject) these methods should all return HRESULT

## Repro steps

1. `NativeMethods.txt` content:
```
RegisterDragDrop
RevokeDragDrop
DragQueryFile
```

2. `NativeMethods.json` content (if present):
```json
```

3. Any of your own code that should be shared?

### Context

- CsWin32 version: [0.2.39-beta]
- Win32Metadata version (if explicitly set by project):
- Target Framework:  net48
- `LangVersion` (if explicitly set by project): [e.g. `9`]

**Comment by AArnott** [comment]
COM methods that return HRESULT by default on the .NET platform return void (or their retval out parameter) instead of HRESULT. So this is by design. The .NET interop marshaler will recognize the HRESULT internally and throw a COMException when an error is returned.

If you want to avoid exceptions, there is a special preserveSig area of the NativeMethods.json file where you can force interfaces or methods to return HRESULT in CsWin32-generated code instead. Or if an API returns S_FALSE or other success codes such that the signature *must* be declared as returning HRESULT to be used properly, please file a bug against the win32metadata repo and they can set a bit in the metadata so that CsWin32 and all other projections know that HRESULT is a requirement for those APIs.
