### ISSUE TITLE
How do you return CLASS_E_NOAGGREGATION from IClassFactory::CreateInstance?

### ISSUE THREAD

**Issue by riverar** [microsoft/CsWin32#732]
I need to be able to return HRESULTs from `IClassFactory::CreateInstance` (e.g. `CLASS_E_NOAGGREGATION`) yet `IClassFactory` is generated with a void return.

```csharp
unsafe void CreateInstance([MarshalAs(UnmanagedType.IUnknown)] object pUnkOuter, global::System.Guid* riid, [MarshalAs(UnmanagedType.IUnknown)] out object ppvObject);
```

0.2.63-beta

**Comment by AArnott** [comment]
Check out https://github.com/microsoft/CsWin32#customizing-generated-code. And even better, check out the description of [this issue](https://github.com/microsoft/win32metadata/issues/1315), which includes a sample of how you can get an HRESULT returned from this method.

Consider commenting on that issue as well if you feel like this API should always return HRESULT instead of throwing on error.
