### ISSUE TITLE
PCSTR.ToString() should convert as an ASCII string 

### ISSUE THREAD

**Issue by harborsiem** [microsoft/CsWin32#761]
## Actual behavior

PCSTR seems to have a wrong Encoding.
See [Data-types](https://learn.microsoft.com/en-us/windows/win32/winprog/windows-data-types)

## Expected behavior

Either documentation or implementation is wrong.

## Repro steps

1. `NativeMethods.txt` content:
```
PSTR
PCSTR
```

2. `NativeMethods.json` content (if present):
```json
```

3. Any of your own code that should be shared?

### Context

- CsWin32 version: [0.2.110-beta]
- Win32Metadata version (if explicitly set by project):
- Target Framework: [net6.0-windows]
- `LangVersion` (if explicitly set by project): [e.g. `9`]

**Comment by AArnott** [comment]
Are you saying that it should use ANSI instead of UTF8 when decoding the bytes? 
I think [wikipedia describes the situation](https://en.wikipedia.org/wiki/ANSI_character_set) well. In the docs, ANSI isn't a particular character set. If we were to be strict about it, I think the correct encoding to use would be whatever the current codepage is for Windows (as returned from [the `GetACP` function](https://learn.microsoft.com/en-us/windows/win32/api/winnls/nf-winnls-getacp)).

A great resource for learning about this is here: https://learn.microsoft.com/en-us/windows/win32/intl/code-pages

In practice, I think many narrow character functions actually assume a UTF-8 encoding, but I'm not sure. 

@mikebattista, thoughts?
