### ISSUE TITLE
Allow specifying platform specific APIs when targeting AnyCPU

### ISSUE THREAD

**Issue by JeremyKuhne** [microsoft/CsWin32#775]
**Is your feature request related to a problem? Please describe.**
Some key APIs such as `SetWindowLongPtr` are needed when targeting `AnyCPU`, even if they are only available on 64 bit. Dynamically choosing the right API depending on the current process state is necessary and a standard pattern.

**Describe the solution you'd like**
I understand that having CsWin32 generate the 32/64 wrapper is out of scope. Consider letting us specify that we want platform specific APIs even when we're targeting `AnyCPU`. Either globally or on an API-by-API basis.

**Describe alternatives you've considered**
Right now the only option is to manually define these P/Invokes.

**Comment by AArnott** [comment]
This sounds nice, and in a subset of cases this may be possible. But we can't do this for all APIs, because certain structs are defined differently based on architecture, and a struct definition from the metadata for amd64 isn't (necessarily) accurate when loaded into a 32-bit process. 

See also #409 #366

**Comment by JeremyKuhne** [comment]
Fwiw I'm fine with this feature having lots of warnings all over it (and would expect it to). Like "x64ApisUnsafe" or whatever. :)

**Comment by AArnott** [comment]
How does this compare with #882?
