### ISSUE TITLE
Not sure how to call MapWindowPoints / MapWindowPoints missing RECT overload

### ISSUE THREAD

**Issue by michael-hawker** [microsoft/CsWin32#789]
## Actual behavior

`MapWindowPoints` can also accept a `Foundation.RECT` type as its third argument:

> /// <param name="lpPoints">A pointer to an array of <a href="https://docs.microsoft.com/previous-versions/dd162805(v=vs.85)">POINT</a> structures that contain the set of points to be converted. The points are in device units. This parameter can also point to a <a href="https://docs.microsoft.com/windows/desktop/api/windef/ns-windef-rect">RECT</a> structure, in which case the <i>cPoints</i> parameter should be set to 2.</param>

However, this overload is not generated. [See example calling methods here](http://pinvoke.net/default.aspx/user32/MapWindowPoints.html).

## Expected behavior

Overload which accepts a `ref RECT` to be included.

I also don't know how to construct a `Span<System.Drawing.Point>` to pass in otherwise...

## Repro steps

1. `NativeMethods.txt` content:
```
MapWindowPoints
```

### Context

- CsWin32 version: 0.2.104-beta
- Target Framework: net6.0-windows10.0.19041.0

Related: https://github.com/microsoft/CsWin32/issues/790

**Comment by AArnott** [comment]
There [is no RECT overload of `MapWindowPoints`](https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-mapwindowpoints). The pinvoke.net declarations you point to are being clever with the fact that RECT happens to match the memory footprint of two POINTs in a row. CsWin32 will never generate something like that. It generates the original definition from the win32 header files, and then often a friendly overload that can make calling it simpler (e.g. use a `ref` instead of a pointer type). But it doesn't generally do anything super insightful like a trick like that.

The docs I link to (the official docs for this or any other API) should tell you what you need to call it. For example the last code sample there shows this:

```c
POINT pt[2];
MapWindowPoints(hWnd1, hWnd2, &pt[0], 1);
MapWindowPoints(hWnd1, hWnd2, &pt[1], 1);
```

But just by reading the docs it seems likely that you could do this in just one step:

```c
MapWindowPoints(hWnd1, hWnd2, &pt[0], 2);
```

You can literally do this in C#:

```cs
using System.Drawing;
using Windows.Win32.Foundation;
using static Windows.Win32.PInvoke;

HWND from, to;
Point[] pts = new Point[2];
unsafe
{
    fixed (Point* p = pts)
    {
        MapWindowPoints(from, to, p, 2);
    }
}
```

But thanks to the friendly overload, you can skip the `unsafe` and `fixed` blocks in this case:

```cs
HWND from, to;
Point[] pts = new Point[2];
MapWindowPoints(from, to, pts);
```

**Comment by michael-hawker** [comment]
Thanks @AArnott for the quick response. I guess it's confusing as the argument generated is listed that it can take a `Span`, but I haven't worked with them too much yet. So I don't think I realized I could just pass in an array directly and have it be cast to the proper type.

The C++ based Win32 docs aren't really friendly to a C# focused developer on how to construct proper input since there's no CsWin32 based example in the docs (even if it ends up being very similar in structure, I know that's part of the point of CsWin32). This ties into the other issue I opened with #790.

That and a better getting started guide/docs for CsWin32 with some common examples for these types of type cases could be really helpful.

**Comment by AArnott** [comment]
`Span<T>` is relatively new, and quite capable. It opens up whole new possibilities that can reduce GC pressure in high performance applications, but many of the common types like arrays and strings that you already use can 'fit' into them. CsWin32 does its best to generate the most modern C# declarations from the native headers possible both for ease of use and perf, but if you're not yet familiar with them, it'll be worth your time to learn about these new .NET types, both for CsWin32 interactions and in the rest of your application.
