### ISSUE TITLE
Add `<example>` tags to generated output

### ISSUE THREAD

**Issue by michael-hawker** [microsoft/CsWin32#790]
**Is your feature request related to a problem? Please describe.**

Not sure if I'm missing more documentation elsewhere, but I keep running into issues trying to adapt existing [PInvoke samples](http://pinvoke.net/default.aspx/user32/MapWindowPoints.html) to use CsWin32 instead.

Usually, it's related to type conversion or calling conventions and such.

**Describe the solution you'd like**

Even if it's a trivial example, it'd be nice for the generated output of the generator to include an `<example>` tag which shows how to call the function including any passed in or referenced pointers/structures.

e.g.

```cs
Span<System.Drawing.Point> points = new();

PInvoke.MapWindowPoints(hWnd, HWND.Null, points);
```

**Describe alternatives you've considered**
Not use CsWin32 and just manually add back the pinvoke calls... 🙁

**Additional context**

Related: https://github.com/microsoft/CsWin32/issues/789

**Comment by AArnott** [comment]
The calling pattern for CsWin32-generated APIs should match what the docs say, and the docs are often linked from the xml doc comments that CsWin32 generates for your convenience. We can't emit examples for these APIs as the docs we have is scraped from the docs site. The docs site will always have more info than the xml doc comments can have.

**Comment by michael-hawker** [comment]
@AArnott appreciate that docs exist, but navigating C++ focused docs as a C# developer isn't always straight-forward, especially when there's casts and other helpers to help interop with C#.

Since the docs are being scrapped and samples exist, it seems like being able to at least put them in the generated xmldoc in an example tag could work? And maybe with some basic inference as done with the APIs themselves to help demonstrate the call patterns better.

At least having some basic guide with some common examples of API calls and conversions to help someone get started more easily with Win32 APIs now that they're more commonly needed for Windows App SDK development would be a big help for someone not as familiar with Win32 APIs nor C++ development in general.

**Comment by AArnott** [comment]
All good points that you're making. But it's unlikely we'll invest more in scraping more than we already are from the docs. The process is _not_ straightforward. We have lots of bugs and enhancements we want to make to CsWin32 itself, and CsWin32 actually just takes the docs as they are scraped (by another repo) so if we really want to add examples to the docs, https://github.com/microsoft/win32metadata would be the place to file that issue anyway since that's where it happens. But if you were to do that, they'd just ask me for my opinion since I wrote the scraper, and I'd say the same thing: it's a lower priority than a lot of the functional bugs we have both in the metadata and in CsWin32 that we're still chasing, so I don't see us working on adding examples in the near future.

As for the docs being C++ focused, you're absolutely right. And there is no funding for rewriting them to be C# focused, either on docs.microsoft.com or for CsWin32 code generation. Win32 programming is in general much harder than C# calling into the .NET BCL, so for folks who have never done it, it'll be a challenge, for sure. CsWin32's scope is _not_ to make that easier except in one respect: declaring the interop APIs. The rest of the challenge remains. Various programming forums will still be a resource, and in fact many of the questions you'll have about it have already been asked and answered in these forums. It'll be a skill though for you to build up to 'translate' many of these from C++ to C# though. 

I like your idea of documenting some common tricks and translations somewhere to help folks in your position to get started. I don't know when we'll get to that, or if the community will send PRs or start a wiki somewhere that can aggregate these ideas.
