### ISSUE TITLE
SetWindowLong / Window_Style incompatible in a weird way

### ISSUE THREAD

**Issue by Gavin-Williams** [microsoft/CsWin32#804]
This is what I was using for fullscreen switch (x64)
```cs
SetWindowLongPtr(Handle, WINDOW_LONG_PTR_INDEX.GWL_STYLE,  (IntPtr)(WS_VISIBLE | WS_POPUP));
```
When I changed to AnyCPU, this function is missing, as reasoned elsewhere. So, I guess we can't use the recommended function, which is compatible with both 32 and 64 bits, because it's also recommended that we compile with AnyCPU and not x64, so there is really only one function we can use... SetWindowLong ?

When I try to just switch over the method to SetWindowLong...
```cs
SetWindowLong(Handle, WINDOW_LONG_PTR_INDEX.GWL_STYLE, (IntPtr)(WS_VISIBLE | WS_POPUP));
```
Error: cannot convert from System.IntPtr to int.

So, just cast to int?

```cs
SetWindowLong(Handle, WINDOW_LONG_PTR_INDEX.GWL_STYLE, (int)(WS_VISIBLE | WS_POPUP));
```
Error: constant cannot be converted to int.

Maybe just pass the flags in the way any C# function would work...

```cs
SetWindowLong(Handle, WINDOW_LONG_PTR_INDEX.GWL_STYLE, WS_VISIBLE | WS_POPUP);  // doesn't work
```
Error: Argument 3; cannot convert from WindowStyle to Int.

Huh?

So I try breaking them up..
```cs
 SetWindowLong(Handle, WINDOW_LONG_PTR_INDEX.GWL_STYLE, (int)WS_VISIBLE); // this is ok
 SetWindowLong(Handle, WINDOW_LONG_PTR_INDEX.GWL_STYLE, (int)WS_POPUP); // this is a constant value
```

I can't work this out. And at this stage I'm thinking you've don't something pretty bad here in terms of common sense for C#, in terms of discoverability.

Also, the enum is of uint type and the argument is an int, how does that even work? See my earlier issue about the same thing ... https://github.com/microsoft/win32metadata/issues/1026

Could you please provide me with a workaround?

**Comment by Gavin-Williams** [comment]
To get this working I used
```cs
unchecked { SetWindowLong(Handle, WINDOW_LONG_PTR_INDEX.GWL_STYLE, (int)(WS_VISIBLE | WS_POPUP)); }
```

**Comment by AArnott** [comment]
> because it's also recommended that we compile with AnyCPU and not x64

Who made that recommendation? In general, it makes a lot of things easier. But once you have to interop with Windows APIs, it can be necessary since the types used can be arch-specific.

> That is so dirty, but I almost don't care anymore

I don't see what the big deal is. `SetWindowLong` is perfectly adequate for setting `WINDOW_STYLE`. The `SetWindowLongPtr` function is useful when you're setting values that may in fact exceed 32-bits, but you're setting 32-bit flags, so `SetWindowLong` is just fine. No hack there.

The only reason you need `unchecked` here is because the `uint` flags you're setting lie outside the `int` range, but is totally a permissible value. You can use an `unchecked` expression instead of an unchecked block to shrink the unchecked region in your code:

```cs
PInvoke.SetWindowLong(h, WINDOW_LONG_PTR_INDEX.GWL_STYLE, unchecked((int)(WINDOW_STYLE.WS_VISIBLE | WINDOW_STYLE.WS_POPUP)))
```
