### ISSUE TITLE
ShellNotifyIcon / NOTIFYICONDATA: szTip and others are read only

### ISSUE THREAD

**Issue by voltagex** [microsoft/CsWin32#83]
Apologies if this is me misunderstanding the Win32 API, but https://docs.microsoft.com/en-us/windows/win32/api/shellapi/ns-shellapi-notifyicondataa seems to suggest I can set the tooltip by providing a value to szTip. It's get-only in the generated code. 

```
            var handle = PInvoke.GetConsoleWindow();
            Microsoft.Windows.Sdk.NOTIFYICONDATAW notifyIcon = new NOTIFYICONDATAW();
            notifyIcon.hWnd = handle;
            notifyIcon.uID = 5;
            notifyIcon.szTip = "test";
```

```
1>C:\git\NotifyTest\NotifyTest\Program.cs(16,13,16,29): error CS0200: Property or indexer 'NOTIFYICONDATAW.szTip' cannot be assigned to -- it is read only
```

**Comment by AArnott** [comment]
`szTip` is defined as a char array with a fixed length embedded in the struct, so you cannot simply assign a managed string to it. Instead, you need to copy the characters into the memory that is within the struct itself. The docs also indicate the string must be null-terminated, but the default C# behavior is to zero-out your locals so just copying in the characters you have should be enough.

Unfortunately, due to https://github.com/microsoft/win32metadata/issues/59, this member is currently generated as `Span<ushort>` instead of `Span<char>`, so an extra cast is required:

```cs
NOTIFYICONDATAW d = default;
"test".AsSpan().CopyTo(MemoryMarshal.Cast<ushort, char>(d.szTip));
```

**Comment by voltagex** [comment]
@AArnott  I'm still seeing this as ushort rather than char even with microsoft/win32metadata#59 fixed. I currently have 

```
<PackageReference Include="Microsoft.Windows.CsWin32" Version="0.1.378-beta">
<PackageReference Include="Microsoft.Windows.SDK.Win32Metadata" Version="10.0.19041.5-preview.22" />
```

**Comment by AArnott** [comment]
Looks like that's a bug still in the metadata. Filed https://github.com/microsoft/win32metadata/issues/285 to track.
