### ISSUE TITLE
Win32 APIs should be automatically projected

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [microsoft/CsWin32#853]
Really CsWin32 shouldn't be a source generator where you need to write a list of function names in a text file and you get the PInvoke for it. All Win32 APIs should be accessible by default from C# (helps with IntelliSense) instead. 

I see things like the [PInvoke library](https://github.com/dotnet/pinvoke) and [Vanara](https://github.com/dahall/Vanara) exist but they're additional dependencies to install.

I would really like to see all the PInvoke-s automatically included when you create a new project targeting Windows specifically (eg: WinForms, WPF or WinUI) and provide Win32 APIs from the start. It should be as easy as including Windows.h in C or C++, easier because C# doesn't need headers.

**Comment by AArnott** [comment]
That would increase the size of your output library or application by around 80MB. With trimming (as yet an imperfect feature), that could be mitigated. When trimming works well, our plan is to produce a nuget package with the full surface area like the PInvoke library. Basically, we'll replace the PInvoke hand-written APIs with CsWin32 generation and push again.

In the meantime, you can use our wildcard patterns in NativeMethods.txt (e.g. `Kernel32.*`) so that you get everything. If you don't mind the increase in size and source generation time, that is.

See also #304, which may address your request, but without any of the downsides.
