### ISSUE TITLE
Regression for `WriteFile` friendly overload

### ISSUE THREAD

**Issue by alexrp** [microsoft/CsWin32#913]
## Actual behavior

![image](https://user-images.githubusercontent.com/44076/231258770-0e93d676-0504-4eea-8436-79903c4d6ea7.png)

## Expected behavior

This overload used to take a `byte*`. `byte?` is definitely not right.

## Repro steps

1. `NativeMethods.txt` content:
```
WriteFile
```

2. `NativeMethods.json` content (if present):
```json
{
  "className": "WindowsPInvoke",
  "allowMarshaling": false,
  "wideCharOnly": false,
  "emitSingleFile": true
}
```

### Context

- CsWin32 version: 0.2.206-beta
- Win32Metadata version (if explicitly set by project): 48.0.19-preview
- Target Framework: net7.0
- `LangVersion` (if explicitly set by project): latest

**Comment by AArnott** [comment]
Thank you for the report. I see in the metadata that this API is declared as:

```cs
public unsafe static extern BOOL WriteFile([In] HANDLE hFile, [Optional][In][Const][MemorySize(BytesParamIndex = 2)] byte* lpBuffer, [In] uint nNumberOfBytesToWrite, [Optional][Out] uint* lpNumberOfBytesWritten, [Optional][In][Out] OVERLAPPED* lpOverlapped);
```

My guess is because `lpBuffer` isn't using the `NativeArrayInfoAttribute` that we decide it isn't an array. I'm not sure if the metadata should be using one or the other, but CsWin32 can be updated to recognize `MemorySize` as well.
